version: '3.8'

services:
  backend:
    build: .
    container_name: dpp-backend-debug
    ports:
      - "8000:8000"
      - "5678:5678"  # Python debugging port
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./digital_persona.db
      - SECRET_KEY=your-secret-key-here-change-in-production
      - DEBUG=true
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
      - ./uploads:/app/uploads
      - ./digital_persona.db:/app/digital_persona.db
    command: >
      sh -c "pip install debugpy -t /tmp && 
             python /tmp/debugpy --listen 0.0.0.0:5678 --wait-for-client -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    restart: unless-stopped

  # Python ML Service with debugging
  python-ml-service:
    build:
      context: ./python-ml-service
      dockerfile: Dockerfile
    container_name: dpp-ml-debug
    ports:
      - "8001:8001"
      - "5679:5679"  # Python ML debugging port
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - ENVIRONMENT=development
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    volumes:
      - ./python-ml-service:/app
      - ./uploads:/app/uploads
      - ./chroma_db:/app/chroma_db
    command: >
      sh -c "pip install debugpy -t /tmp && 
             python /tmp/debugpy --listen 0.0.0.0:5679 --wait-for-client -m uvicorn main:app --host 0.0.0.0 --port 8001 --reload"
    restart: unless-stopped

  # Redis for debugging
  redis:
    image: redis:alpine
    container_name: dpp-redis-debug
    ports:
      - "6379:6379"
    volumes:
      - redis_debug_data:/data
    restart: unless-stopped

volumes:
  redis_debug_data:

networks:
  default:
    name: digital-persona-debug-network 