global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Digital Persona Platform Backend
  - job_name: "dpp-backend"
    static_configs:
      - targets: ["backend:8000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # Digital Persona Platform Frontend
  - job_name: "dpp-frontend"
    static_configs:
      - targets: ["frontend:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s
    scrape_timeout: 10s

  # PostgreSQL Database
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    scrape_interval: 30s

  # Redis Cache
  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    scrape_interval: 30s

  # Nginx
  - job_name: "nginx"
    static_configs:
      - targets: ["nginx:80"]
    scrape_interval: 30s
