"""Add AI capabilities tables

Revision ID: bbd3b7642cef
Revises: 1f3296ad01bd
Create Date: 2025-07-06 00:03:20.492594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbd3b7642cef'
down_revision: Union[str, Sequence[str], None] = '1f3296ad01bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: SQLite doesn't support ALTER COLUMN for nullability changes
    # The columns already exist from previous migration, so we skip those operations
    
    # Add new columns to personas table
    op.add_column('personas', sa.Column('personality_traits', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('voice_settings', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('memory_enabled', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('personas', sa.Column('learning_enabled', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('personas', sa.Column('image_analysis_enabled', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('personas', sa.Column('voice_synthesis_enabled', sa.Boolean(), nullable=False, server_default='1'))
    op.add_column('personas', sa.Column('learned_preferences', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('conversation_patterns', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('emotional_responses', sa.JSON(), nullable=True))
    op.add_column('personas', sa.Column('memory_context', sa.Text(), nullable=True))
    op.add_column('personas', sa.Column('last_interaction', sa.DateTime(), nullable=True))
    op.add_column('personas', sa.Column('interaction_count', sa.Integer(), nullable=False, server_default='0'))
    
    # Create new tables for AI capabilities
    op.create_table('persona_memories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('image_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_file_id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('analysis_type', sa.String(length=50), nullable=False),
    sa.Column('results', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('voice_syntheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('audio_file_path', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('voice_settings', sa.JSON(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_table('personality_learnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('persona_id', sa.Integer(), nullable=False),
    sa.Column('learning_type', sa.String(length=50), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_conversation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personality_learnings')
    op.drop_table('voice_syntheses')
    op.drop_table('image_analyses')
    op.drop_table('persona_memories')
    op.drop_column('personas', 'interaction_count')
    op.drop_column('personas', 'last_interaction')
    op.drop_column('personas', 'memory_context')
    op.drop_column('personas', 'emotional_responses')
    op.drop_column('personas', 'conversation_patterns')
    op.drop_column('personas', 'learned_preferences')
    op.drop_column('personas', 'voice_synthesis_enabled')
    op.drop_column('personas', 'image_analysis_enabled')
    op.drop_column('personas', 'learning_enabled')
    op.drop_column('personas', 'memory_enabled')
    op.drop_column('personas', 'voice_settings')
    op.drop_column('personas', 'personality_traits')
    # ### end Alembic commands ###
