name: Debug Workflow

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-west-1

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check GitHub secrets
        run: |
          echo "Checking if AWS_ROLE_ARN secret is set..."
          if [ -n "${{ secrets.AWS_ROLE_ARN }}" ]; then
            echo "✅ AWS_ROLE_ARN is set"
            echo "Role ARN: ${{ secrets.AWS_ROLE_ARN }}"
          else
            echo "❌ AWS_ROLE_ARN is not set"
          fi

      - name: Test AWS credentials
        if: secrets.AWS_ROLE_ARN != ''
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Test AWS access
        if: secrets.AWS_ROLE_ARN != ''
        run: |
          echo "Testing AWS access..."
          aws sts get-caller-identity
          aws ec2 describe-instances --max-items 1 --query 'Reservations[0].Instances[0].InstanceId' --output text

      - name: Check file structure
        run: |
          echo "Checking file structure..."
          ls -la
          echo "Frontend directory:"
          ls -la frontend/
          echo "Backend directory:"
          ls -la app/

      - name: Check Python setup
        run: |
          echo "Checking Python setup..."
          python --version
          if [ -f "requirements.txt" ]; then
            echo "✅ requirements.txt exists"
            head -5 requirements.txt
          else
            echo "❌ requirements.txt not found"
          fi

      - name: Check Node.js setup
        run: |
          echo "Checking Node.js setup..."
          node --version
          npm --version
          if [ -f "frontend/package.json" ]; then
            echo "✅ frontend/package.json exists"
            cat frontend/package.json | grep -A 5 '"scripts"'
          else
            echo "❌ frontend/package.json not found"
          fi

      - name: Check Terraform setup
        run: |
          echo "Checking Terraform setup..."
          if [ -f "terraform/environments/main/main.tf" ]; then
            echo "✅ Terraform main.tf exists"
          else
            echo "❌ Terraform main.tf not found"
          fi
