#!/bin/bash

# =================================
# SETUP ENVIRONMENT
# =================================
# This script sets up the environment variables for any sub-environment
# Usage: ./setup-environment.sh [environment]
# Example: ./setup-environment.sh dev01

set -e

# Source the environment configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/config/environment.sh"

# Function to display usage
usage() {
    echo "Usage: $0 [environment]"
    echo ""
    echo "Examples:"
    echo "  $0 dev01    # Set up dev01 environment"
    echo "  $0 dev99    # Set up dev99 environment"
    echo "  $0 qa27     # Set up qa27 environment"
    echo "  $0 staging01 # Set up staging01 environment"
    echo ""
    echo "This script will:"
    echo "  1. Detect the correct API URL for the environment"
    echo "  2. Set up environment variables"
    echo "  3. Create a .env file for the frontend"
    echo "  4. Display connection information"
}

# Function to create .env file for frontend
create_env_file() {
    local env="$1"
    local api_url="$2"
    
    local env_file=".env"
    local env_aws_file=".env.aws"
    
    echo "📝 Creating environment configuration files..." >&2
    
    # Create .env file for frontend
    cat > "$env_file" << EOF
# ====================================
# 🌩️ DYNAMIC ENVIRONMENT CONFIGURATION
# ====================================
# Generated by setup-environment.sh for $env
# Generated at: $(date)

# 🔌 API Configuration  
NEXT_PUBLIC_API_URL="$api_url/api/trpc"
PORT=4000

# 🌐 Frontend Configuration
FRONTEND_PORT=3000

# 🎯 Development Features
NODE_ENV="development"
CORS_ORIGIN="http://localhost:3000,http://127.0.0.1:3000"

# 🔗 Database (AWS Aurora + RDS Proxy)
# Note: Database URL should be set in your AWS environment
DATABASE_URL="postgresql://dpp_admin:your-password@your-rds-proxy:5432/digital_persona"

# 🪣 File Storage (AWS S3)
S3_BUCKET="local-mars-dpp-uploads"
AWS_REGION="us-west-1"

# 🔐 AWS Credentials (Set these to your AWS user credentials)
# Get these from: aws configure list
AWS_ACCESS_KEY_ID="your-aws-access-key-id"
AWS_SECRET_ACCESS_KEY="your-aws-secret-access-key"

# 💰 Cost-Optimized Infrastructure Info
# Your AWS environment: $env
# Website: https://$env.hibiji.com
# API: $api_url
EOF

    # Create .env.aws file (backup of AWS-specific config)
    cp "$env_file" "$env_aws_file"
    
    echo "✅ Created $env_file and $env_aws_file" >&2
}

# Function to test API connectivity
test_api_connectivity() {
    local api_url="$1"
    
    echo "🔍 Testing API connectivity..." >&2
    
    # Test health endpoint
    local health_url="$api_url/health"
    if curl -s --head "$health_url" >/dev/null 2>&1; then
        echo "✅ API health check passed: $health_url" >&2
        return 0
    else
        echo "⚠️  API health check failed: $health_url" >&2
        echo "💡 The API might be starting up or not accessible yet" >&2
        return 1
    fi
}

# Function to display environment information
display_environment_info() {
    local env="$1"
    local api_url="$2"
    
    echo ""
    echo "=========================================="
    echo "🌍 ENVIRONMENT SETUP COMPLETE"
    echo "=========================================="
    echo "Environment: $env"
    echo "API URL: $api_url"
    echo "Frontend URL: https://$env.hibiji.com"
    echo "Health Check: $api_url/health"
    echo "=========================================="
    echo ""
    echo "🚀 Next steps:"
    echo "  1. Start the frontend: npm run dev"
    echo "  2. The frontend will connect to: $api_url/api/trpc"
    echo "  3. Test login at: https://$env.hibiji.com"
    echo ""
    echo "🔧 Environment variables are set in .env file"
    echo "📝 You can edit .env to customize settings"
    echo ""
}

# Main function
main() {
    local target_env="${1:-$ENVIRONMENT}"
    
    if [[ -z "$target_env" ]]; then
        echo "❌ No environment specified and no default environment detected" >&2
        usage
        exit 1
    fi
    
    if [[ "$1" == "-h" || "$1" == "--help" ]]; then
        usage
        exit 0
    fi
    
    echo "🌍 Setting up environment: $target_env" >&2
    
    # Get the API URL for the environment
    echo "🔍 Getting API URL for $target_env..." >&2
    local api_url
    if ! api_url=$("$SCRIPT_DIR/get-environment-api-url.sh" "$target_env"); then
        echo "❌ Failed to get API URL for environment: $target_env" >&2
        echo "💡 Make sure the environment is deployed and accessible" >&2
        exit 1
    fi
    
    echo "✅ Found API URL: $api_url" >&2
    
    # Test API connectivity
    test_api_connectivity "$api_url"
    
    # Create environment files
    create_env_file "$target_env" "$api_url"
    
    # Display information
    display_environment_info "$target_env" "$api_url"
    
    echo "🎉 Environment setup complete for $target_env!" >&2
}

# Run main function
main "$@"
